weight = float(input("Введите ваш вес (кг): "))
height = float(input("Введите ваш рост (м): "))
bmi = weight / (height ** 2)
print("--- Отчёт о состоянии здоровья ---")
print(f"Рост: {height} м\nВес: {weight} кг")
print(f"Индекс массы тела: {bmi:.2f}")