dna = input("Введите последовательность ДНК: ").upper()
count_A = dna.count("A")
count_T = dna.count("T")
count_G = dna.count("G")
count_C = dna.count("C")
length = len(dna)
print("=== Анализ последовательности ДНК ===\n")
print(f"Последовательность ДНК в верхнем регистре: {dna}\n")
print(f"Подсчёт нуклеотидов: \nA: {count_A}\nT: {count_T}\nG: {count_G}\nС: {count_C}\n")
print(f"Общая длина: {length} нуклеотидов")
print("\nПроцентное содержание нуклеотидов:")
print(f"A: {count_A / length * 100:.2f}%\nT: {count_T / length * 100:.2f}%\nG: {count_G / length * 100:.2f}%\nC: {count_C / length * 100:.2f}%")